### ISSUE TITLE
Cleaning company names

### ISSUE THREAD

**Issue by gtmaskall** [TishaSanMiguel/Springboard_DataWrangling_Ex1#1]
The gsub function calls should achieve the desired effect, but currently don't assign the result.
After your call to glimpse (line 4), check the distinct values of company you're starting with. These are what you want to clean up. You can do this by inserting 
`raw_data %>% distinct(company)`
Then put your gsub calls into a mutate thus:
```
raw_data <- raw_data %>%
    mutate(company = gsub(pattern = "[p|P|f].*", replacement = "philips", x = company),
                company = gsub(pattern = "[a|A].*", replacement = "azko", x = company),
                ...)
```
After this, check the result with 
`raw_data %>% distinct(company)`
You should see only the correct company names you want. If that's correct, you can close this issue and move on to the next step.

**Comment by TishaSanMiguel** [comment]
It worked :)  The only thing that I cannot make work is the third task which is to populate the product category to define the product.  I used case_when but I'm out of ideas of what to do with it now.

**Comment by gtmaskall** [comment]
I see it. You're using double quotes around your product code variable. This is causing R to treat it as a character string, not a variable. In other words, you're testing whether the string "product code" is equal to the string "p", and of course it isn't. If you don't have any special characters in your column name then you don't need quotes of any kind, but you have a space so you do. Use backticks in place of double quotes.
single quote = '
double quote = "
backtick = `

**Comment by TishaSanMiguel** [comment]
excuse me as I celebrate.  2 months later and I have finally finished my first exercise.  Thank you for your help and support.  On to the next one!

**Comment by gtmaskall** [comment]
Cool. I think we can close this issue now then. ;-)
